const test=require('node:test'),assert=require('node:assert/strict'),Game=require('../src/Game'),Player=require('../src/Player'),{TYPES}=require('../src/constants');
test('Deck enthält 108 Karten',()=>{const Deck=require('../src/Deck');assert.equal(new Deck().cards.length,108)});
test('Zwei Spieler: Reverse überspringt',()=>{const g=new Game('ABC','a');g.addPlayer(new Player('a','A'));g.addPlayer(new Player('b','B'));g.start();g.discard=[{color:'red',type:TYPES.REVERSE}];g.currentColor='red';g.currentIndex=0;g.players.get('a').hand=[{color:'red',type:TYPES.REVERSE}];g.play('a',0);assert.equal(g.current().id,'a')});
test('Wild Draw Four nur ohne passende Farbe',()=>{const g=new Game('ABC','a');const a=new Player('a','A'),b=new Player('b','B');g.addPlayer(a);g.addPlayer(b);g.start();g.discard=[{color:'red',type:TYPES.NUMBER,value:4}];g.currentColor='red';g.currentIndex=0;a.hand=[{color:'red',type:TYPES.NUMBER,value:2},{color:null,type:TYPES.WILD_DRAW_FOUR}];assert.equal(g.play('a',1,'blue').error,'+4 nur ohne passende Farbe erlaubt')});

test('Out-of-turn und nicht besessene Karten werden abgewiesen',()=>{const g=new Game('ABC','a');const a=new Player('a','A'),b=new Player('b','B');g.addPlayer(a);g.addPlayer(b);g.start();g.currentIndex=0;g.discard=[{color:'red',type:TYPES.NUMBER,value:1}];g.currentColor='red';g.pendingDraw=0;a.hand=[{color:'red',type:TYPES.NUMBER,value:2}];b.hand=[{color:'red',type:TYPES.NUMBER,value:3}];assert.match(g.play('b',0).error,/Nicht am Zug/);assert.match(g.play('a',1).error,/Nicht am Zug|ungültige/)});
test('Letzte Karte beendet Runde und vergibt Punkte',()=>{const g=new Game('ABC','a');const a=new Player('a','A'),b=new Player('b','B');g.addPlayer(a);g.addPlayer(b);g.start();g.currentIndex=0;g.discard=[{color:'red',type:TYPES.NUMBER,value:1}];g.currentColor='red';g.pendingDraw=0;a.hand=[{color:'red',type:TYPES.NUMBER,value:2}];b.hand=[{color:'blue',type:TYPES.NUMBER,value:7}];const r=g.play('a',0);assert.equal(r.roundEnd,true);assert.equal(g.started,false);assert.equal(a.score,7)});
test('Leerer Nachziehstapel wird aus Ablage aufgefüllt',()=>{const g=new Game('ABC','a');const a=new Player('a','A'),b=new Player('b','B');g.addPlayer(a);g.addPlayer(b);g.start();g.deck.cards=[];g.discard=[{color:'red',type:TYPES.NUMBER,value:1},{color:'blue',type:TYPES.NUMBER,value:2},{color:'green',type:TYPES.NUMBER,value:3}];g.currentIndex=0;g.currentColor='green';a.hand=[];const r=g.draw('a');assert.ok(r.card);assert.equal(g.discard.length,1)});
test('Ein einzelner verbleibender Spieler beendet bei Disconnect den laufenden Zug',()=>{const g=new Game('ABC','a');const a=new Player('a','A'),b=new Player('b','B');g.addPlayer(a);g.addPlayer(b);g.start();g.currentIndex=1;b.connected=false;g.normalizeTurn();assert.equal(g.current().id,'a')});
test('Ungültige Wild-Farbe wird abgewiesen',()=>{const g=new Game('ABC','a');const a=new Player('a','A'),b=new Player('b','B');g.addPlayer(a);g.addPlayer(b);g.start();g.currentIndex=0;g.discard=[{color:'red',type:TYPES.NUMBER,value:1}];g.currentColor='red';g.pendingDraw=0;a.hand=[{color:null,type:TYPES.WILD}];assert.match(g.play('a',0,'purple').error,/Farbe/)});
