const Deck=require('./Deck'),{COLORS,TYPES,UNO_TIMEOUT}=require('./constants');
class Game{
 constructor(code,hostId,settings={}){Object.assign(this,{code,hostId,players:new Map(),settings:{stacking:false,...settings},deck:new Deck(),discard:[],currentColor:null,currentIndex:0,direction:1,started:false,roundWinner:null,pendingDraw:0,unoTimers:new Map()})}
 get list(){return [...this.players.values()]}
 get connected(){return this.list.filter(p=>p.connected)}
 addPlayer(p){this.players.set(p.id,p)}
 removePlayer(id){this.clearUno(id);this.players.delete(id);if(this.hostId===id)this.transferHost();this.normalizeTurn()}
 transferHost(){this.hostId=this.connected[0]?.id||this.list[0]?.id||null}
 clearUno(id){const t=this.unoTimers.get(id);if(t)clearTimeout(t);this.unoTimers.delete(id)}
 clearTimers(){for(const id of this.unoTimers.keys())this.clearUno(id)}
 normalizeTurn(){if(!this.started)return;if(!this.connected.length){this.started=false;return}let p=this.current();if(!p||!p.connected){for(let i=0;i<this.list.length;i++){this.advance();if(this.current()?.connected)break}}}
 take(){if(!this.deck.cards.length&&this.discard.length>1){const top=this.discard.pop();this.deck.cards=this.discard.splice(0);this.deck.shuffle();this.discard=[top]}return this.deck.draw()}
 start(){if(this.connected.length<2)return false;this.clearTimers();this.started=true;this.roundWinner=null;this.pendingDraw=0;this.direction=1;this.currentIndex=0;this.deck=new Deck;this.discard=[];for(const p of this.list){p.hand=[];p.unoCalled=false;for(let i=0;i<7;i++)p.hand.push(this.take())}let c;do{c=this.take()}while(c&&c.type===TYPES.WILD_DRAW_FOUR);if(!c)return false;this.discard=[c];this.currentColor=c.color||COLORS[0];if(c.type===TYPES.WILD)this.currentColor=COLORS[Math.floor(Math.random()*4)];if(c.type===TYPES.SKIP||(c.type===TYPES.REVERSE&&this.list.length===2))this.advance(1);if(c.type===TYPES.DRAW_TWO){this.pendingDraw=2;this.advance(1)}return true}
 current(){return this.list[this.currentIndex]}
 advance(n=1){if(!this.list.length)return;for(let i=0;i<n;i++)this.currentIndex=(this.currentIndex+this.direction+this.list.length)%this.list.length;this.normalizeTurn()}
 canPlay(c){const t=this.discard.at(-1);if(!c||!t)return false;if(this.pendingDraw)return this.settings.stacking&&(c.type===t.type||c.type===TYPES.WILD_DRAW_FOUR);return c.type===TYPES.WILD||c.type===TYPES.WILD_DRAW_FOUR||c.color===this.currentColor||c.type===t.type||(c.type===TYPES.NUMBER&&t.type===TYPES.NUMBER&&c.value===t.value)}
 canWDF(p){return !p.hand.some(c=>c.color===this.currentColor)}
 points(c){return c.type===TYPES.NUMBER?c.value:(c.type===TYPES.WILD||c.type===TYPES.WILD_DRAW_FOUR?50:20)}
 play(id,index,color){const p=this.players.get(id),c=p?.hand[index];if(!p||!p.connected||p!==this.current()||!Number.isInteger(index)||index<0||index>=p.hand.length)return{error:'Nicht am Zug oder ungültige Karte'};if(!this.canPlay(c))return{error:'Karte kann nicht gespielt werden'};if(c.type===TYPES.WILD_DRAW_FOUR&&!this.canWDF(p))return{error:'+4 nur ohne passende Farbe erlaubt'};if((c.type===TYPES.WILD||c.type===TYPES.WILD_DRAW_FOUR)&&!COLORS.includes(color))return{error:'Farbe fehlt'};if(c.type!==TYPES.WILD&&c.type!==TYPES.WILD_DRAW_FOUR&&color!==undefined)return{error:'Ungültige Farbe'};p.hand.splice(index,1);this.discard.push(c);this.currentColor=c.color||color;p.unoCalled=false;this.clearUno(p.id);if(p.hand.length===1){this.unoTimers.set(p.id,setTimeout(()=>{if(this.started&&p.hand.length===1&&!p.unoCalled){for(let i=0;i<2;i++){const card=this.take();if(card)p.hand.push(card)}}this.clearUno(p.id)},UNO_TIMEOUT))}if(!p.hand.length){this.roundWinner=p;this.started=false;this.clearTimers();p.score+=this.list.filter(x=>x!==p).reduce((s,x)=>s+x.hand.reduce((a,z)=>a+this.points(z),0),0);return{card:c,roundEnd:true}}if(c.type===TYPES.DRAW_TWO||c.type===TYPES.WILD_DRAW_FOUR){this.pendingDraw+=c.type===TYPES.DRAW_TWO?2:4;this.advance()}else if(c.type===TYPES.SKIP)this.advance(2);else if(c.type===TYPES.REVERSE){if(this.list.length>2)this.direction*=-1;this.advance()}else this.advance();return{card:c}}
 draw(id){const p=this.players.get(id);if(!p||!p.connected||p!==this.current())return{error:'Nicht am Zug'};if(this.pendingDraw&&!this.settings.stacking){for(let i=0;i<this.pendingDraw;i++){const c=this.take();if(c)p.hand.push(c)}this.pendingDraw=0;this.advance();return{drawn:true}}if(this.pendingDraw)return{error:'Du musst stapeln oder ziehen'};const c=this.take();if(c)p.hand.push(c);return{card:c}}
 callUno(id){const p=this.players.get(id);if(!p||!p.connected||p.hand.length!==1)return false;p.unoCalled=true;this.clearUno(id);return true}
 serialize(v){return{code:this.code,hostId:this.hostId,settings:this.settings,started:this.started,currentPlayerId:this.current()?.id,currentColor:this.currentColor,topCard:this.discard.at(-1),players:this.list.map(p=>({id:p.id,name:p.name,cardCount:p.hand.length,score:p.score,connected:p.connected})),hand:this.players.get(v)?.hand||[],roundWinner:this.roundWinner?.id||null,pendingDraw:this.pendingDraw}}
}
module.exports=Game;
